import type { User, Post, Department, Event, Group, Story, StoryHighlight, Notification } from './types'

export const departments: Department[] = [
  { id: 'dept-1', name: 'Engineering' },
  { id: 'dept-2', name: 'Marketing' },
  { id: 'dept-3', name: 'Human Resources' },
  { id: 'dept-4', name: 'Finance' },
  { id: 'dept-5', name: 'Sales' },
]

export const users: User[] = [
  {
    id: 'user-1',
    name: 'Nguyen Van A',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user1',
    department: departments[0],
    email: 'nguyenvana@company.com',
    profile: {
      bio: 'Senior Software Engineer voi 5 nam kinh nghiem. Dam me ve React, TypeScript va xay dung san pham.',
      location: 'Ha Noi, Viet Nam',
      hometown: 'Nam Dinh',
      birthday: new Date('1995-03-15'),
      gender: 'male',
      coverImage: 'https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?w=1200&q=80',
      socialLinks: {
        facebook: 'https://facebook.com/nguyenvana',
        linkedin: 'https://linkedin.com/in/nguyenvana',
        github: 'https://github.com/nguyenvana',
        website: 'https://nguyenvana.dev',
      },
      joinedAt: new Date('2022-01-15'),
      achievements: [
        {
          id: 'ach-1',
          title: 'Nhan vien xuat sac Q4/2025',
          description: 'Duoc binh chon la nhan vien xuat sac quy 4 nam 2025',
          icon: 'trophy',
          date: new Date('2025-12-15'),
        },
        {
          id: 'ach-2',
          title: 'Hoan thanh 100 task',
          description: 'Da hoan thanh 100 task dung deadline',
          icon: 'check-circle',
          date: new Date('2025-09-20'),
        },
        {
          id: 'ach-3',
          title: 'Mentor cua nam',
          description: 'Huong dan thanh cong 5 nhan vien moi',
          icon: 'users',
          date: new Date('2025-06-10'),
        },
      ],
      interests: [
        { id: 'int-1', name: 'React & TypeScript', icon: 'code' },
        { id: 'int-2', name: 'UI/UX Design', icon: 'palette' },
        { id: 'int-3', name: 'Bong da', icon: 'trophy' },
        { id: 'int-4', name: 'Doc sach', icon: 'book' },
        { id: 'int-5', name: 'Du lich', icon: 'plane' },
      ],
      featuredStories: [
        {
          id: 'feat-1',
          name: 'Niem Vui',
          coverImage: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400&q=80',
          storyIds: ['story-1', 'story-2'],
        },
        {
          id: 'feat-2',
          name: 'Cong viec',
          coverImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=400&q=80',
          storyIds: ['story-3'],
        },
        {
          id: 'feat-3',
          name: 'Du lich',
          coverImage: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=400&q=80',
          storyIds: ['story-4', 'story-5'],
        },
      ],
    },
  },
  {
    id: 'user-2',
    name: 'Tran Thi B',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user2',
    department: departments[1],
    email: 'tranthib@company.com',
    profile: {
      bio: 'Marketing Manager - Chuyen gia ve Digital Marketing va Brand Strategy.',
      location: 'Ho Chi Minh, Viet Nam',
      hometown: 'Da Nang',
      birthday: new Date('1993-07-22'),
      gender: 'female',
      coverImage: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=1200&q=80',
      socialLinks: {
        facebook: 'https://facebook.com/tranthib',
        linkedin: 'https://linkedin.com/in/tranthib',
      },
      joinedAt: new Date('2021-06-01'),
    },
  },
  {
    id: 'user-3',
    name: 'Le Van C',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user3',
    department: departments[2],
    email: 'levanc@company.com',
    profile: {
      bio: 'HR Manager - Xay dung van hoa doanh nghiep va phat trien nhan tai.',
      location: 'Ha Noi, Viet Nam',
      hometown: 'Hai Phong',
      birthday: new Date('1990-12-10'),
      gender: 'male',
      coverImage: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=1200&q=80',
      socialLinks: {
        linkedin: 'https://linkedin.com/in/levanc',
      },
      joinedAt: new Date('2020-03-15'),
    },
  },
  {
    id: 'user-4',
    name: 'Pham Thi D',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user4',
    department: departments[3],
    email: 'phamthid@company.com',
    profile: {
      bio: 'Finance Director - Quan ly tai chinh va ke hoach ngan sach cong ty.',
      location: 'Ha Noi, Viet Nam',
      hometown: 'Thanh Hoa',
      birthday: new Date('1988-05-28'),
      gender: 'female',
      coverImage: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=1200&q=80',
      socialLinks: {
        linkedin: 'https://linkedin.com/in/phamthid',
      },
      joinedAt: new Date('2019-08-20'),
    },
  },
  {
    id: 'user-5',
    name: 'Hoang Van E',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user5',
    department: departments[4],
    email: 'hoangvane@company.com',
    profile: {
      bio: 'Sales Manager - Chuyen gia ban hang B2B va xay dung quan he khach hang.',
      location: 'Ho Chi Minh, Viet Nam',
      hometown: 'Can Tho',
      birthday: new Date('1992-09-05'),
      gender: 'male',
      coverImage: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=1200&q=80',
      socialLinks: {
        facebook: 'https://facebook.com/hoangvane',
        linkedin: 'https://linkedin.com/in/hoangvane',
      },
      joinedAt: new Date('2021-02-10'),
    },
  },
]

export const currentUser = users[0]

export const initialPosts: Post[] = [
  {
    id: 'post-1',
    authorId: 'user-2',
    content: 'Xin chao tat ca moi nguoi! Tuan nay chung ta se co buoi team building vao thu 6. Moi nguoi nho dang ky tham gia nhe!',
    visibility: 'company',
    attachments: [
      {
        id: 'att-1',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=640&q=80',
        name: 'team-building.jpg',
      },
    ],
    poll: {
      id: 'poll-1',
      question: 'Ban co the tham gia team building khong?',
      options: [
        { id: 'opt-1', text: 'Co, toi se tham gia', votes: ['user-1', 'user-3'] },
        { id: 'opt-2', text: 'Khong, toi ban', votes: ['user-4'] },
        { id: 'opt-3', text: 'Chua chac chan', votes: [] },
      ],
      multipleChoice: false,
    },
    taggedUsers: ['user-1', 'user-3', 'user-4', 'user-5'],
    reactions: [
      { emoji: '👍', users: ['user-1', 'user-3', 'user-5'] },
      { emoji: '❤️', users: ['user-4'] },
    ],
    comments: [
      {
        id: 'cmt-1',
        authorId: 'user-3',
        content: 'Tuyet voi! Toi rat mong cho!',
        createdAt: new Date(Date.now() - 3600000),
        reactions: [
          { emoji: '👍', users: ['user-1', 'user-2'] },
          { emoji: '❤️', users: ['user-5'] },
        ],
        replies: [
          {
            id: 'reply-1',
            authorId: 'user-1',
            content: 'Toi cung vay, se rat vui!',
            createdAt: new Date(Date.now() - 1800000),
            reactions: [{ emoji: '❤️', users: ['user-3'] }],
            parentId: 'cmt-1',
            replies: [],
          },
          {
            id: 'reply-2',
            authorId: 'user-5',
            content: 'Moi nguoi nho chuan bi do thoai mai nhe!',
            createdAt: new Date(Date.now() - 900000),
            reactions: [],
            parentId: 'cmt-1',
            replies: [],
          },
        ],
      },
    ],
    createdAt: new Date(Date.now() - 86400000),
    updatedAt: new Date(Date.now() - 86400000),
    isPublished: true,
  },
  {
    id: 'post-2',
    authorId: 'user-1',
    content: 'Thong bao: He thong se bao tri vao toi thu 7, tu 22:00 - 02:00. Moi nguoi luu y de tranh mat du lieu nhe.',
    visibility: 'department',
    visibleToDepartments: ['dept-1'],
    attachments: [],
    taggedUsers: [],
    reactions: [
      { emoji: '👀', users: ['user-2'] },
    ],
    comments: [],
    createdAt: new Date(Date.now() - 172800000),
    updatedAt: new Date(Date.now() - 172800000),
    isPublished: true,
  },
  {
    id: 'post-3',
    authorId: 'user-4',
    content: 'Bao cao tai chinh quy 4 da hoan thanh. Vui long xem file dinh kem va cho y kien.',
    visibility: 'specific',
    visibleTo: ['user-1', 'user-2'],
    attachments: [],
    taggedUsers: ['user-1', 'user-2'],
    reactions: [],
    comments: [],
    createdAt: new Date(Date.now() - 259200000),
    updatedAt: new Date(Date.now() - 259200000),
    isPublished: true,
  },
]

export const stickers = [
  'https://media.giphy.com/media/l0MYGb1LuZ3n7IVrO/giphy.gif',
  'https://media.giphy.com/media/l41lFw057lAJQMwg0/giphy.gif',
  'https://media.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif',
  'https://media.giphy.com/media/xT5LMHxhOfscxPfIfm/giphy.gif',
]

export const commonEmojis = ['👍', '❤️', '😂', '😮', '😢', '😡', '🎉', '🔥', '👏', '💯']

export const storyReactionEmojis = ['❤️', '😂', '😮', '😢', '🔥', '👏']

export const initialStories: Story[] = [
  {
    id: 'story-1',
    authorId: 'user-2',
    media: {
      id: 'sm-1',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&q=80',
    },
    text: 'Team meeting sang nay',
    textPosition: { x: 50, y: 80 },
    textColor: '#ffffff',
    backgroundColor: '#000000',
    visibility: 'company',
    taggedUsers: ['user-1'],
    reactions: [
      { id: 'sr-1', userId: 'user-1', emoji: '🔥', createdAt: new Date(Date.now() - 3600000) },
      { id: 'sr-2', userId: 'user-3', emoji: '❤️', createdAt: new Date(Date.now() - 7200000) },
    ],
    replies: [
      { id: 'srp-1', userId: 'user-1', message: 'Rat tuyet voi!', createdAt: new Date(Date.now() - 1800000) },
    ],
    views: [
      { userId: 'user-1', viewedAt: new Date(Date.now() - 3600000) },
      { userId: 'user-3', viewedAt: new Date(Date.now() - 7200000) },
      { userId: 'user-4', viewedAt: new Date(Date.now() - 10800000) },
    ],
    isHighlight: false,
    createdAt: new Date(Date.now() - 4 * 3600000),
    expiresAt: new Date(Date.now() + 20 * 3600000),
  },
  {
    id: 'story-2',
    authorId: 'user-2',
    media: {
      id: 'sm-2',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=80',
    },
    text: 'Coffee break',
    textPosition: { x: 50, y: 90 },
    textColor: '#ffffff',
    visibility: 'company',
    taggedUsers: [],
    reactions: [
      { id: 'sr-3', userId: 'user-5', emoji: '☕', createdAt: new Date(Date.now() - 1800000) },
    ],
    replies: [],
    views: [
      { userId: 'user-1', viewedAt: new Date(Date.now() - 1800000) },
      { userId: 'user-5', viewedAt: new Date(Date.now() - 3600000) },
    ],
    isHighlight: false,
    createdAt: new Date(Date.now() - 2 * 3600000),
    expiresAt: new Date(Date.now() + 22 * 3600000),
  },
  {
    id: 'story-3',
    authorId: 'user-3',
    media: {
      id: 'sm-3',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80',
    },
    text: 'Workshop HR hom nay',
    textPosition: { x: 50, y: 85 },
    textColor: '#ffffff',
    backgroundColor: '#6366f1',
    visibility: 'department',
    visibleToDepartments: ['dept-3'],
    taggedUsers: ['user-4'],
    reactions: [],
    replies: [],
    views: [
      { userId: 'user-4', viewedAt: new Date(Date.now() - 5400000) },
    ],
    isHighlight: true,
    highlightName: 'Workshop',
    createdAt: new Date(Date.now() - 6 * 3600000),
    expiresAt: new Date(Date.now() + 18 * 3600000),
  },
  {
    id: 'story-4',
    authorId: 'user-5',
    media: {
      id: 'sm-4',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=800&q=80',
    },
    text: 'Gap khach hang moi!',
    textPosition: { x: 50, y: 75 },
    textColor: '#ffffff',
    visibility: 'company',
    taggedUsers: [],
    reactions: [
      { id: 'sr-4', userId: 'user-1', emoji: '👏', createdAt: new Date(Date.now() - 900000) },
      { id: 'sr-5', userId: 'user-2', emoji: '🎉', createdAt: new Date(Date.now() - 1200000) },
    ],
    replies: [],
    views: [
      { userId: 'user-1', viewedAt: new Date(Date.now() - 900000) },
      { userId: 'user-2', viewedAt: new Date(Date.now() - 1200000) },
    ],
    isHighlight: false,
    createdAt: new Date(Date.now() - 1 * 3600000),
    expiresAt: new Date(Date.now() + 23 * 3600000),
  },
  {
    id: 'story-5',
    authorId: 'user-1',
    media: {
      id: 'sm-5',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&q=80',
    },
    text: 'Coding session',
    textPosition: { x: 50, y: 90 },
    textColor: '#00ff00',
    backgroundColor: '#1a1a2e',
    visibility: 'company',
    taggedUsers: ['user-5'],
    reactions: [
      { id: 'sr-6', userId: 'user-2', emoji: '🔥', createdAt: new Date(Date.now() - 600000) },
    ],
    replies: [],
    views: [
      { userId: 'user-2', viewedAt: new Date(Date.now() - 600000) },
    ],
    isHighlight: true,
    highlightName: 'Work',
    createdAt: new Date(Date.now() - 30 * 60000),
    expiresAt: new Date(Date.now() + 23.5 * 3600000),
  },
]

export const initialStoryHighlights: StoryHighlight[] = [
  {
    id: 'highlight-1',
    userId: 'user-1',
    name: 'Work',
    coverStoryId: 'story-5',
    storyIds: ['story-5'],
    createdAt: new Date(Date.now() - 7 * 24 * 3600000),
  },
  {
    id: 'highlight-2',
    userId: 'user-3',
    name: 'Workshop',
    coverStoryId: 'story-3',
    storyIds: ['story-3'],
    createdAt: new Date(Date.now() - 14 * 24 * 3600000),
  },
]

export const initialGroups: Group[] = [
  {
    id: 'group-1',
    name: 'Frontend Developers',
    description: 'Nhom danh cho cac lap trinh vien Frontend. Chia se kien thuc, thu thuat va xu huong moi nhat ve React, Vue, Angular...',
    coverImage: 'https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?w=800&q=80',
    visibility: 'public',
    members: [
      { userId: 'user-1', role: 'admin', joinedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000) },
      { userId: 'user-2', role: 'moderator', joinedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000) },
      { userId: 'user-5', role: 'member', joinedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000) },
    ],
    joinRequests: [
      { id: 'req-1', userId: 'user-4', message: 'Toi muon hoc them ve Frontend', createdAt: new Date(Date.now() - 86400000), status: 'pending' },
    ],
    invitations: [],
    posts: [
      {
        id: 'gpost-1',
        groupId: 'group-1',
        authorId: 'user-1',
        content: 'React 19 da chinh thuc ra mat! Cac ban da thu cac tinh nang moi chua? Server Components va Actions thuc su rat manh me.',
        attachments: [
          { id: 'gatt-1', type: 'image', url: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=640&q=80', name: 'react-19.jpg' }
        ],
        taggedUsers: ['user-2'],
        reactions: [{ emoji: '🔥', users: ['user-2', 'user-5'] }],
        comments: [
          { id: 'gcmt-1', authorId: 'user-2', content: 'Tuyet voi! Dang apply vao du an moi', createdAt: new Date(Date.now() - 3600000), reactions: [] }
        ],
        isPinned: true,
        isHidden: false,
        isApproved: true,
        createdAt: new Date(Date.now() - 86400000),
        updatedAt: new Date(Date.now() - 86400000),
      },
      {
        id: 'gpost-2',
        groupId: 'group-1',
        authorId: 'user-5',
        content: 'Ai co kinh nghiem voi TailwindCSS v4 chua? Nghe noi co nhieu thay doi lon.',
        attachments: [],
        taggedUsers: [],
        reactions: [{ emoji: '👍', users: ['user-1'] }],
        comments: [],
        isPinned: false,
        isHidden: false,
        isApproved: true,
        createdAt: new Date(Date.now() - 172800000),
        updatedAt: new Date(Date.now() - 172800000),
      }
    ],
    requirePostApproval: false,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    createdBy: 'user-1',
  },
  {
    id: 'group-2',
    name: 'HR & Tuyen dung',
    description: 'Nhom noi bo cua phong Nhan su. Thao luan ve quy trinh tuyen dung, chinh sach nhan su va cac van de lien quan.',
    coverImage: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=800&q=80',
    visibility: 'private',
    members: [
      { userId: 'user-3', role: 'admin', joinedAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000) },
      { userId: 'user-4', role: 'moderator', joinedAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000) },
    ],
    joinRequests: [],
    invitations: [
      { id: 'inv-1', groupId: 'group-2', invitedUserId: 'user-1', invitedBy: 'user-3', createdAt: new Date(Date.now() - 86400000), status: 'pending' },
    ],
    posts: [
      {
        id: 'gpost-3',
        groupId: 'group-2',
        authorId: 'user-3',
        content: 'Thong bao: Quy trinh tuyen dung moi se ap dung tu thang sau. Moi nguoi xem file dinh kem.',
        attachments: [],
        taggedUsers: ['user-4'],
        reactions: [{ emoji: '👀', users: ['user-4'] }],
        comments: [],
        isPinned: true,
        isHidden: false,
        isApproved: true,
        createdAt: new Date(Date.now() - 259200000),
        updatedAt: new Date(Date.now() - 259200000),
      }
    ],
    requirePostApproval: true,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
    createdBy: 'user-3',
  },
  {
    id: 'group-3',
    name: 'Coffee & Chat',
    description: 'Nhom giai tri, chia se nhung cau chuyen vui ve, thu gian sau gio lam viec. Moi nguoi deu duoc chao don!',
    coverImage: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80',
    visibility: 'public',
    members: [
      { userId: 'user-2', role: 'admin', joinedAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000) },
      { userId: 'user-1', role: 'member', joinedAt: new Date(Date.now() - 80 * 24 * 60 * 60 * 1000) },
      { userId: 'user-3', role: 'member', joinedAt: new Date(Date.now() - 70 * 24 * 60 * 60 * 1000) },
      { userId: 'user-4', role: 'member', joinedAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000) },
      { userId: 'user-5', role: 'moderator', joinedAt: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000) },
    ],
    joinRequests: [],
    invitations: [],
    posts: [],
    requirePostApproval: false,
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000),
    createdBy: 'user-2',
  },
]

export const initialEvents: Event[] = [
  {
    id: 'event-1',
    title: 'Team Building Cuoi Nam 2026',
    description: 'Cung nhau tham gia cac hoat dong team building vui nhon, tao su gan ket giua cac thanh vien trong cong ty. Chuong trinh bao gom: tro choi nhom, BBQ, va van nghe.',
    type: 'party',
    coverImage: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&q=80',
    location: 'Resort Flamingo Dai Lai',
    isOnline: false,
    startDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    endDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000),
    organizerId: 'user-3',
    participants: ['user-1', 'user-2', 'user-4'],
    maxParticipants: 50,
    visibility: 'company',
    createdAt: new Date(Date.now() - 86400000),
  },
  {
    id: 'event-2',
    title: 'Workshop: AI trong Phat trien San pham',
    description: 'Hoi thao chuyen de ve ung dung AI vao quy trinh phat trien san pham, tu y tuong den hien thuc. Dien gia: CTO Nguyen Van A.',
    type: 'workshop',
    coverImage: 'https://images.unsplash.com/photo-1591453089816-0fbb971b454c?w=800&q=80',
    location: 'Phong hop A301',
    isOnline: true,
    meetingUrl: 'https://meet.google.com/abc-defg-hij',
    startDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    endDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000),
    organizerId: 'user-1',
    participants: ['user-2', 'user-5'],
    maxParticipants: 30,
    visibility: 'company',
    createdAt: new Date(Date.now() - 172800000),
  },
  {
    id: 'event-3',
    title: 'Hop Kiem Diem Quy 1/2026',
    description: 'Cuoc hop dinh ky de danh gia ket qua kinh doanh quy 1 va lap ke hoach cho quy 2.',
    type: 'meeting',
    location: 'Phong hop chinh',
    isOnline: true,
    meetingUrl: 'https://zoom.us/j/123456789',
    startDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    endDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000),
    organizerId: 'user-4',
    participants: ['user-1', 'user-2', 'user-3', 'user-5'],
    visibility: 'company',
    createdAt: new Date(Date.now() - 259200000),
  },
]

export const initialNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-1',
    fromUserId: 'user-2',
    type: 'like',
    postId: 'post-1',
    content: 'Liked your post',
    isRead: false,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
  },
  {
    id: 'notif-2',
    userId: 'user-1',
    fromUserId: 'user-3',
    type: 'comment',
    postId: 'post-1',
    content: 'Commented on your post',
    isRead: false,
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
  },
  {
    id: 'notif-3',
    userId: 'user-1',
    fromUserId: 'user-4',
    type: 'mention',
    postId: 'post-2',
    content: 'Mentioned you in a post',
    isRead: true,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: 'notif-4',
    userId: 'user-1',
    fromUserId: 'user-5',
    type: 'friend_request',
    content: 'Sent you a friend request',
    isRead: false,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
  },
  {
    id: 'notif-5',
    userId: 'user-1',
    fromUserId: 'user-2',
    type: 'story',
    content: 'Posted a new story',
    isRead: true,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
  },
]
